project_id = "zprlfecbvdltfpneidte"

[functions.get-fishing-advice-mock]
verify_jwt = false

[functions.get-weather-forecast]
verify_jwt = false

[functions.create-share-link]
verify_jwt = true

[functions.share-via-email]
verify_jwt = true

[functions.get-shared-report]
verify_jwt = false